# Generated by Django 3.2.18 on 2023-03-08 06:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(verbose_name='Deadline (MM/DD/YYYY)')),
            ],
        ),
    ]
