# Generated by Django 3.2.18 on 2023-05-02 04:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Pemicu', max_length=100)),
                ('content', tinymce.models.HTMLField(default=' ')),
                ('date', models.DateTimeField(auto_now=True)),
                ('thread', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initial_post', to='forum.thread')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Pendapat', max_length=100)),
                ('content', tinymce.models.HTMLField(default=' ')),
                ('date', models.DateTimeField(auto_now=True)),
                ('initial_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='post.initialpost')),
            ],
        ),
        migrations.CreateModel(
            name='NestedReplyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Pendapat', max_length=100)),
                ('content', tinymce.models.HTMLField(default=' ')),
                ('date', models.DateTimeField(auto_now=True)),
                ('reply_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_reply_post', to='post.replypost')),
            ],
        ),
    ]
