# Generated by Django 3.2.18 on 2023-03-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initialpost_nestedreplypost_replypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialpost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='nestedreplypost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='nestedreplypost',
            old_name='reply_post_id',
            new_name='reply_post',
        ),
        migrations.RenameField(
            model_name='replypost',
            old_name='initial_post_id',
            new_name='initial_post',
        ),
        migrations.RenameField(
            model_name='replypost',
            old_name='post_id',
            new_name='post',
        ),
    ]
