# Generated by Django 3.2.18 on 2023-03-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='reply_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='initial_post',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='post',
        ),
        migrations.DeleteModel(
            name='InitialPost',
        ),
        migrations.DeleteModel(
            name='NestedReplyPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ReplyPost',
        ),
    ]
