# Generated by Django 3.2.18 on 2023-03-09 17:25

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_initialpost_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='post',
        ),
        migrations.AddField(
            model_name='initialpost',
            name='content',
            field=tinymce.models.HTMLField(default=' '),
        ),
        migrations.AddField(
            model_name='initialpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Deadline (MM/DD/YYYY)'),
        ),
        migrations.AddField(
            model_name='initialpost',
            name='tag',
            field=models.CharField(default='Pemicu', max_length=100),
        ),
        migrations.AddField(
            model_name='initialpost',
            name='title',
            field=models.CharField(default='Title-1', max_length=100),
        ),
        migrations.AddField(
            model_name='nestedreplypost',
            name='content',
            field=tinymce.models.HTMLField(default=' '),
        ),
        migrations.AddField(
            model_name='nestedreplypost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Deadline (MM/DD/YYYY)'),
        ),
        migrations.AddField(
            model_name='nestedreplypost',
            name='tag',
            field=models.CharField(default='Pendapat', max_length=100),
        ),
        migrations.AddField(
            model_name='nestedreplypost',
            name='title',
            field=models.CharField(default='Title-1', max_length=100),
        ),
        migrations.AddField(
            model_name='replypost',
            name='content',
            field=tinymce.models.HTMLField(default=' '),
        ),
        migrations.AddField(
            model_name='replypost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Deadline (MM/DD/YYYY)'),
        ),
        migrations.AddField(
            model_name='replypost',
            name='tag',
            field=models.CharField(default='Pendapat', max_length=100),
        ),
        migrations.AddField(
            model_name='replypost',
            name='title',
            field=models.CharField(default='Title-1', max_length=100),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
