# Generated by Django 3.2.18 on 2023-03-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_initialpost_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='title',
        ),
    ]
