# Generated by Django 3.2.18 on 2023-05-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_auto_20230310_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialpost',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initial_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
