# Generated by Django 3.2.18 on 2023-05-04 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0015_auto_20230504_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='initialpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='initialpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='initialpost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='initialpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='user',
        ),
        migrations.AlterField(
            model_name='nestedreplypost',
            name='reply_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nested_reply_post', to='post.replypost'),
        ),
        migrations.AlterField(
            model_name='replypost',
            name='initial_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='post.initialpost'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Pemicu', max_length=100)),
                ('content', tinymce.models.HTMLField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='initialpost',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initial_post', to='post.post'),
        ),
        migrations.AddField(
            model_name='nestedreplypost',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nested_reply_post', to='post.post'),
        ),
        migrations.AddField(
            model_name='replypost',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_post', to='post.post'),
        ),
    ]
