# Generated by Django 3.2.18 on 2023-05-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20230504_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='nestedreplypost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='post',
        ),
    ]
