# Generated by Django 3.2.18 on 2023-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
    ]
