# Generated by Django 3.2.18 on 2023-03-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
