# Generated by Django 3.2.18 on 2023-03-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_week'),
        ('forum', '0003_initial'),
    ]

    operations = [
    ]
