# Generated by Django 3.2.18 on 2023-03-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20230310_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('mecanism_expectation', models.CharField(max_length=500)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_guide', to='forum.thread')),
            ],
        ),
        migrations.AddField(
            model_name='inquiryphase',
            name='discussion_guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.discussionguide'),
        ),
    ]
