# Generated by Django 3.2.18 on 2023-03-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_merge_0002_alter_thread_week_0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
    ]
