# Generated by Django 3.2.18 on 2023-03-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_week'),
        ('forum', '0003_initial'),
        ('forum', '0004_auto_20230310_1305'),
    ]

    operations = [
    ]
