# Generated by Django 3.2.18 on 2023-03-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
