# Generated by Django 3.2.18 on 2023-03-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_merge_20230313_1042'),
        ('forum', '0006_thread_title'),
    ]

    operations = [
    ]
