# Generated by Django 3.2.18 on 2023-03-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_merge_0005_merge_20230313_1042_0006_thread_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionguide',
            old_name='mecanism_expectation',
            new_name='mechanism_expectation',
        ),
        migrations.AddField(
            model_name='discussionguide',
            name='state',
            field=models.CharField(choices=[('1', 'Phase1'), ('2', 'Phase2'), ('3', 'Phase3'), ('4', 'Phase4')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='discussionguide',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_guide', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='referencefile',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_file', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.week'),
        ),
        migrations.DeleteModel(
            name='InquiryPhase',
        ),
    ]
