# Generated by Django 3.2.18 on 2023-05-08 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_auto_20230315_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Phase1'), ('2', 'Phase2'), ('3', 'Phase3'), ('4', 'Phase4')], default=None, max_length=255)),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_onboarding', to='forum.thread')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
