# Generated by Django 3.2.18 on 2023-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20230315_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionguide',
            name='state',
            field=models.CharField(choices=[('1', 'Phase1'), ('2', 'Phase2'), ('3', 'Phase3'), ('4', 'Phase4'), ('5', 'Phase5')], default='1', max_length=255),
        ),
    ]
