# Generated by Django 3.2.18 on 2023-05-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0004_alter_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
